// ignore_for_file: type=lint, unused_field, non_constant_identifier_names

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: unused_import, unused_element, deprecated_member_use_from_same_package
import 'dart:ffi' as ffi;

/// Bindings cho LoopCore C API (engine/include/le/engine_api.h).
/// File sinh tự động — KHÔNG sửa tay. Chạy scripts/gen_bindings.sh.
///
class LoopCoreBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  LoopCoreBindings(ffi.DynamicLibrary dynamicLibrary) : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  LoopCoreBindings.fromLookup(ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup)
    : _lookup = lookup;

  /// ───────────── Hàm ─────────────
  int le_api_version() {
    return _le_api_version();
  }

  late final _le_api_versionPtr = _lookup<ffi.NativeFunction<ffi.Int32 Function()>>('le_api_version');
  late final _le_api_version = _le_api_versionPtr.asFunction<int Function()>();

  int le_audio_start() {
    return _le_audio_start();
  }

  late final _le_audio_startPtr = _lookup<ffi.NativeFunction<ffi.Int32 Function()>>('le_audio_start');
  late final _le_audio_start = _le_audio_startPtr.asFunction<int Function()>();

  void le_audio_stop() {
    return _le_audio_stop();
  }

  late final _le_audio_stopPtr = _lookup<ffi.NativeFunction<ffi.Void Function()>>('le_audio_stop');
  late final _le_audio_stop = _le_audio_stopPtr.asFunction<void Function()>();

  ffi.Pointer<ffi.Char> le_call(ffi.Pointer<ffi.Char> requestJson) {
    return _le_call(requestJson);
  }

  late final _le_callPtr = _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>)>>(
    'le_call',
  );
  late final _le_call = _le_callPtr.asFunction<ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>)>();

  int le_create(ffi.Pointer<LeConfig> config) {
    return _le_create(config);
  }

  late final _le_createPtr = _lookup<ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<LeConfig>)>>('le_create');
  late final _le_create = _le_createPtr.asFunction<int Function(ffi.Pointer<LeConfig>)>();

  void le_destroy() {
    return _le_destroy();
  }

  late final _le_destroyPtr = _lookup<ffi.NativeFunction<ffi.Void Function()>>('le_destroy');
  late final _le_destroy = _le_destroyPtr.asFunction<void Function()>();

  void le_free_string(ffi.Pointer<ffi.Char> s) {
    return _le_free_string(s);
  }

  late final _le_free_stringPtr = _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Char>)>>(
    'le_free_string',
  );
  late final _le_free_string = _le_free_stringPtr.asFunction<void Function(ffi.Pointer<ffi.Char>)>();

  int le_get_peaks(ffi.Pointer<ffi.Char> clipId, int level, ffi.Pointer<ffi.Float> outMinMax, int maxPairs) {
    return _le_get_peaks(clipId, level, outMinMax, maxPairs);
  }

  late final _le_get_peaksPtr =
      _lookup<
        ffi.NativeFunction<ffi.Int32 Function(ffi.Pointer<ffi.Char>, ffi.Int32, ffi.Pointer<ffi.Float>, ffi.Int32)>
      >('le_get_peaks');
  late final _le_get_peaks = _le_get_peaksPtr
      .asFunction<int Function(ffi.Pointer<ffi.Char>, int, ffi.Pointer<ffi.Float>, int)>();

  void le_read_state(ffi.Pointer<LeState> out) {
    return _le_read_state(out);
  }

  late final _le_read_statePtr = _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<LeState>)>>('le_read_state');
  late final _le_read_state = _le_read_statePtr.asFunction<void Function(ffi.Pointer<LeState>)>();

  bool le_send(ffi.Pointer<LeCommand> cmd) {
    return _le_send(cmd);
  }

  late final _le_sendPtr = _lookup<ffi.NativeFunction<ffi.Bool Function(ffi.Pointer<LeCommand>)>>('le_send');
  late final _le_send = _le_sendPtr.asFunction<bool Function(ffi.Pointer<LeCommand>)>();

  void le_set_event_callback(LeEventCallback cb) {
    return _le_set_event_callback(cb);
  }

  late final _le_set_event_callbackPtr = _lookup<ffi.NativeFunction<ffi.Void Function(LeEventCallback)>>(
    'le_set_event_callback',
  );
  late final _le_set_event_callback = _le_set_event_callbackPtr.asFunction<void Function(LeEventCallback)>();
}

const int LE_API_VERSION = 1;

const int LE_MAX_SCENES = 8;

const int LE_MAX_TRACKS = 8;

sealed class LeClipState {
  static const LE_CLIP_EMPTY = 0;
  static const LE_CLIP_STOPPED = 1;
  static const LE_CLIP_QUEUED_PLAY = 2;
  static const LE_CLIP_PLAYING = 3;
  static const LE_CLIP_QUEUED_STOP = 4;
  static const LE_CLIP_QUEUED_RECORD = 5;
  static const LE_CLIP_RECORDING = 6;
  static const LE_CLIP_OVERDUBBING = 7;
}

/// ───────────── Lệnh RT (đường nhanh) ─────────────
final class LeCommand extends ffi.Struct {
  /// LeCommandType
  @ffi.Uint16()
  external int type;

  /// 0..7, -1 = không áp dụng / master
  @ffi.Int8()
  external int track;

  /// 0..7 (scene hoặc FX slot), -1 = không áp dụng
  @ffi.Int8()
  external int slot;

  @ffi.Int32()
  external int i0;

  @ffi.Float()
  external double f0;

  @ffi.Float()
  external double f1;

  @ffi.Double()
  external double d0;

  /// 0 = xử lý ở block kế tiếp
  @ffi.Int64()
  external int hostTimeNs;

  static ffi.Pointer<LeCommand> $allocate(
    ffi.Allocator $allocator, {
    required int type,
    required int track,
    required int slot,
    required int i0,
    required double f0,
    required double f1,
    required double d0,
    required int hostTimeNs,
  }) => $allocator<LeCommand>()
    ..ref.type = type
    ..ref.track = track
    ..ref.slot = slot
    ..ref.i0 = i0
    ..ref.f0 = f0
    ..ref.f1 = f1
    ..ref.d0 = d0
    ..ref.hostTimeNs = hostTimeNs;
}

sealed class LeCommandType {
  /// Transport
  static const LE_CMD_TRANSPORT_PLAY = 1;
  static const LE_CMD_TRANSPORT_STOP = 2;

  /// d0 = bpm (20..300)
  static const LE_CMD_SET_BPM = 3;

  /// i0 = LeQuantize
  static const LE_CMD_SET_QUANTIZE = 4;

  /// i0 = 0 tắt / 1 bật / 2 chỉ khi thu; f0 = volume 0..1
  static const LE_CMD_METRONOME = 5;

  /// i0 = số bar 0..2
  static const LE_CMD_SET_COUNT_IN = 6;

  /// track, slot
  static const LE_CMD_CLIP_LAUNCH = 10;

  /// track
  static const LE_CMD_CLIP_STOP = 11;

  /// slot = scene
  static const LE_CMD_SCENE_LAUNCH = 12;
  static const LE_CMD_STOP_ALL = 13;

  /// track, slot, i0 = số bar (0 = tự do)
  static const LE_CMD_CLIP_RECORD = 14;

  /// track: kết thúc take tự do tại ranh giới quantize
  static const LE_CMD_RECORD_STOP = 15;

  /// track
  static const LE_CMD_OVERDUB_TOGGLE = 16;

  /// track, slot (-1 = tự chọn): nút LOOP xoay vòng thu → chốt → overdub (07 §3.1b)
  static const LE_CMD_LOOP_BUTTON = 17;

  /// track, f0 = dB (-120 = -inf .. +6)
  static const LE_CMD_TRACK_GAIN = 20;

  /// track, f0 = -1..1
  static const LE_CMD_TRACK_PAN = 21;

  /// track, i0 = 0/1
  static const LE_CMD_TRACK_MUTE = 22;

  /// track, i0 = 0/1
  static const LE_CMD_TRACK_SOLO = 23;

  /// track, i0 = 0/1 (phía main cấp phát buffer thu trước khi enqueue)
  static const LE_CMD_TRACK_ARM = 24;

  /// track, i0 = 0 off / 1 auto / 2 on
  static const LE_CMD_TRACK_MONITOR = 25;

  /// track: nhận nốt từ MIDI controller
  static const LE_CMD_SELECT_TRACK = 26;

  /// track, i0 = note 0..127, f0 = velocity 0..1
  static const LE_CMD_NOTE_ON = 30;

  /// track, i0 = note
  static const LE_CMD_NOTE_OFF = 31;

  /// track (-1 = mọi track)
  static const LE_CMD_ALL_NOTES_OFF = 32;

  /// track (-1 = master), slot = fx index, i0 = paramId, f0 = value
  static const LE_CMD_FX_PARAM = 40;

  /// track, slot, i0 = 0/1
  static const LE_CMD_FX_BYPASS = 41;

  /// f0 = dB
  static const LE_CMD_MASTER_GAIN = 42;

  /// f0 = Hz, f1 = gain 0..1 (0 = tắt)
  static const LE_CMD_SPIKE_SINE = 900;

  /// i0 = số voice giả lập tải (0..128)
  static const LE_CMD_SPIKE_LOAD_VOICES = 901;

  /// i0 = ms: thu mic vào RAM (tối đa 10000)
  static const LE_CMD_SPIKE_RECORD = 902;

  /// i0 = 1 phát loop / 0 dừng
  static const LE_CMD_SPIKE_PLAY_RECORD = 903;

  /// i0 = 0/1: mic → loa (dùng tai nghe!)
  static const LE_CMD_SPIKE_PASSTHROUGH = 904;
}

/// ───────────── Cấu hình ─────────────
final class LeConfig extends ffi.Struct {
  /// = LE_API_VERSION, engine từ chối nếu lệch
  @ffi.Int32()
  external int apiVersion;

  /// 128
  @ffi.Int32()
  external int preferredBufferSize;

  /// 48000
  @ffi.Double()
  external double preferredSampleRate;

  /// 1 (mic) hoặc 2 (interface)
  @ffi.Int32()
  external int numInputChannels;

  @ffi.Int32()
  external int _reserved;

  /// Documents/ của app, UTF-8
  external ffi.Pointer<ffi.Char> dataDir;

  /// thư mục thư viện âm thanh đóng gói
  external ffi.Pointer<ffi.Char> libraryDir;

  static ffi.Pointer<LeConfig> $allocate(
    ffi.Allocator $allocator, {
    required int apiVersion,
    required int preferredBufferSize,
    required double preferredSampleRate,
    required int numInputChannels,
    required int $reserved,
    required ffi.Pointer<ffi.Char> dataDir,
    required ffi.Pointer<ffi.Char> libraryDir,
  }) => $allocator<LeConfig>()
    ..ref.apiVersion = apiVersion
    ..ref.preferredBufferSize = preferredBufferSize
    ..ref.preferredSampleRate = preferredSampleRate
    ..ref.numInputChannels = numInputChannels
    ..ref._reserved = $reserved
    ..ref.dataDir = dataDir
    ..ref.libraryDir = libraryDir;
}

/// ───────────── Mã lỗi ─────────────
sealed class LeError {
  static const LE_OK = 0;
  static const LE_ERR_INVALID_ARG = -1;
  static const LE_ERR_NOT_CREATED = -2;
  static const LE_ERR_ALREADY_CREATED = -3;
  static const LE_ERR_API_VERSION = -4;
  static const LE_ERR_NOT_IMPLEMENTED = -5;
  static const LE_ERR_AUDIO_DEVICE = -10;
  static const LE_ERR_MIC_PERMISSION = -11;
  static const LE_ERR_FILE_NOT_FOUND = -20;
  static const LE_ERR_FILE_FORMAT = -21;
  static const LE_ERR_DISK_FULL = -22;
  static const LE_ERR_OUT_OF_MEMORY = -30;
  static const LE_ERR_QUEUE_FULL = -31;
  static const LE_ERR_JOB_CANCELLED = -40;
  static const LE_ERR_JOB_NOT_FOUND = -41;
  static const LE_ERR_PITCH_NOT_DETECTED = -50;

  /// LE_EVT_ERROR: không vào được overdub (Re-Pitch khác tempo, chưa có bản copy)
  static const LE_ERR_OVERDUB_UNSUPPORTED = -60;
  static const LE_ERR_INTERNAL = -99;
}

typedef LeEventCallback =
    ffi.Pointer<
      ffi.NativeFunction<ffi.Void Function(ffi.Int32 type, ffi.Int32 a, ffi.Int32 b, ffi.Int64 jobId, ffi.Double value)>
    >;

/// ───────────── Event (engine → UI, bất đồng bộ; tham số theo giá trị) ─────────────
sealed class LeEventType {
  /// a = track, b = slot
  static const LE_EVT_RECORDING_FINISHED = 1;

  /// jobId, value = 0..1
  static const LE_EVT_JOB_PROGRESS = 2;

  /// jobId
  static const LE_EVT_JOB_DONE = 3;

  /// jobId, a = LeError
  static const LE_EVT_JOB_FAILED = 4;

  /// a = tổng số xrun
  static const LE_EVT_XRUN = 5;

  /// a = 1 bắt đầu / 0 kết thúc
  static const LE_EVT_AUDIO_INTERRUPTED = 6;

  /// a = 1 nếu tai nghe có dây/interface, b = 1 nếu Bluetooth
  static const LE_EVT_ROUTE_CHANGED = 7;

  /// value = bpm (từ Link)
  static const LE_EVT_TEMPO_CHANGED = 8;

  /// a = số peer
  static const LE_EVT_LINK_PEERS = 9;

  /// danh sách đổi → gọi midi.listDevices
  static const LE_EVT_MIDI_DEVICES = 10;

  /// a = kind (0 note, 1 cc), b = number
  static const LE_EVT_MIDI_LEARNED = 11;

  /// a = LeError
  static const LE_EVT_ERROR = 12;

  /// value = MB đang dùng
  static const LE_EVT_MEMORY_WARNING = 13;

  /// a = track, b = slot: nội dung clip MIDI đổi phía engine (overdub MIDI) → đọc lại
  /// clip.getMidi. ≤ 10 lần/s mỗi ô; luôn có 1 lần cuối trước RECORDING_FINISHED
  static const LE_EVT_CLIP_CHANGED = 14;
}

sealed class LeQuantize {
  static const LE_Q_NONE = 0;
  static const LE_Q_1_16 = 1;
  static const LE_Q_1_8 = 2;
  static const LE_Q_1_4 = 3;
  static const LE_Q_1_2 = 4;
  static const LE_Q_1_BAR = 5;
  static const LE_Q_2_BAR = 6;
  static const LE_Q_4_BAR = 7;
}

/// ───────────── Trạng thái (engine → UI, đọc mỗi frame bằng le_read_state) ─────────────
final class LeState extends ffi.Struct {
  /// tăng mỗi lần audio thread publish
  @ffi.Uint32()
  external int publishCounter;

  @ffi.Uint8()
  external int playing;

  @ffi.Uint8()
  external int anyRecording;

  @ffi.Uint8()
  external int linkEnabled;

  @ffi.Uint8()
  external int linkPeers;

  /// vị trí transport (beat) tại đầu block gần nhất
  @ffi.Double()
  external double beat;

  @ffi.Double()
  external double bpm;

  @ffi.Double()
  external double sampleRate;

  @ffi.Int32()
  external int bufferSize;

  @ffi.Int32()
  external int beatsPerBar;

  /// LeQuantize
  @ffi.Int32()
  external int quantize;

  @ffi.Int32()
  external int latencyRoundTripSamples;

  /// 0..1, trung bình 1 giây
  @ffi.Float()
  external double cpuLoad;

  /// 0..1, max trong 1 giây
  @ffi.Float()
  external double cpuPeak;

  @ffi.Uint32()
  external int xrunCount;

  @ffi.Int32()
  external int activeVoices;

  /// 0..1 tuyến tính
  @ffi.Float()
  external double inputPeak;

  @ffi.Array.multi([2])
  external ffi.Array<ffi.Float> masterPeak;

  @ffi.Array.multi([8, 2])
  external ffi.Array<ffi.Array<ffi.Float>> trackPeak;

  /// LeClipState
  @ffi.Array.multi([8, 8])
  external ffi.Array<ffi.Array<ffi.Uint8>> clipState;

  /// -1 nếu không phát
  @ffi.Array.multi([8])
  external ffi.Array<ffi.Int8> trackPlayingSlot;

  /// 0..1 vị trí trong clip đang phát/thu
  @ffi.Array.multi([8])
  external ffi.Array<ffi.Float> trackClipProgress;
}
